server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.url=${REDIS_URL:rediss://default:gQAAAAAAAlXzAAIgcDFmNWI3MmMwMWE1MmM0MWNjOWVjYWZkNGM2MjY3Y2ZkMA@loving-gobbler-153075.upstash.io:6379}
# spring.cache.type=redis
# spring.cache.redis.time-to-live=10s
